server:
  port: 9004

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hms_payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

clients:
  gatewayBaseUrl: http://localhost:8081
  internalKey: "CHANGE_ME_INTERNAL_KEY"

app:
  frontendBaseUrl: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
