server:
  port: 9004

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hms_payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

clients:
  gatewayBaseUrl: http://localhost:8081
  internalKey: "CHANGE_ME_INTERNAL_KEY"

app:
  frontendBaseUrl: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmnCode: R2Z4WA60
  hashSecret: OKTUC610AJCZEXM962OGVOGJRL5Q83EX
  returnUrl: http://localhost:8081/api/payments/vnpay/return
